version: "3.8"

services:
  nginx:
    image: garud6209/retail-store-react:latest
    container_name: nginx-react-app
    restart: unless-stopped
    ports:
      - "8081:80" # Serve React via Nginx
    networks:
      - retail_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the custom Nginx config
    environment:
      - VITE_API_URL=http://retail-store:8080 # Pass the API URL to React at build time

  retail-store:
    image: garud6209/retail-store:latest
    container_name: retail-spring-test
    ports:
      - "8080:8080" # Backend API
    networks:
      - retail_app
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  retail_app:
    driver: bridge
