services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - retail_app
    volumes:
      - D:\Major-Project\Spring-revision\Git-Sync\retail-store-react\dist:/usr/share/nginx/html
      - D:\Major-Project\Spring-revision\Git-Sync\retail-store-react\nginx.conf:/etc/nginx/nginx.conf

  retail-store:
    image: garud6209/retail-store:latest
    container_name: retail-store
    ports:
      - "8080:8080" # Adjust as needed
    networks:
      - retail_app
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  retail-store-react:
    image: garud6209/retail-store-react:latest
    container_name: retail-store-react
    ports:
      - "3000:3000" # Port for React frontend
    networks:
      - retail_app
    environment:
      - VITE_API_URL=http://retail-store:8080 # Backend API URL

networks:
  retail_app:
    driver: bridge
